name: Deploy Frontend

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chataffy-frontend .
          docker push ${{ secrets.DOCKER_USERNAME }}/chataffy-frontend

      - name: Deploy Frontend to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/chataffy/chataffy_fe
            git pull origin main
            cd ..
            docker-compose stop frontend
            docker pull ${{ secrets.DOCKER_USERNAME }}/chataffy-frontend
            docker-compose up -d frontend
